ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS starting_price INTEGER,
ADD COLUMN IF NOT EXISTS bank_name TEXT,
ADD COLUMN IF NOT EXISTS account_number TEXT,
ADD COLUMN IF NOT EXISTS account_name TEXT,
ADD COLUMN IF NOT EXISTS service_title TEXT,
ADD COLUMN IF NOT EXISTS last_reset_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS emergency_contact_name TEXT,
ADD COLUMN IF NOT EXISTS emergency_contact_phone TEXT,
ADD COLUMN IF NOT EXISTS theme_mode TEXT DEFAULT 'auto',
ADD COLUMN IF NOT EXISTS notification_preferences JSONB,
ADD COLUMN IF NOT EXISTS worker_rating_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS worker_avg_rating NUMERIC(3,2) DEFAULT 0.00;
